<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>JetPack_2</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="PNG\Jetpack2Label.png" />
    <None Remove="PNG\Jetpack3Logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="PNG\Jetpack2Label.png" />
    <Resource Include="PNG\Jetpack3Logo.png" />
  </ItemGroup>

</Project>
